// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwU8AKRzNRjy-XxvkDb2GnwLNfymCSYls',
    appId: '1:763835643480:web:00614b9fb2f7906312bc2d',
    messagingSenderId: '763835643480',
    projectId: 'facebook-clone-67188',
    authDomain: 'facebook-clone-67188.firebaseapp.com',
    storageBucket: 'facebook-clone-67188.firebasestorage.app',
    measurementId: 'G-XKZ1VY0TRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqeGoAhv8yosyNfalT4duI9V2QKNAgoNM',
    appId: '1:763835643480:android:18806c982dbeb6b712bc2d',
    messagingSenderId: '763835643480',
    projectId: 'facebook-clone-67188',
    storageBucket: 'facebook-clone-67188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHHXA3MQymoST6FCV313Wq9IwtVpt_ImE',
    appId: '1:763835643480:ios:537bfb1e196ef8d512bc2d',
    messagingSenderId: '763835643480',
    projectId: 'facebook-clone-67188',
    storageBucket: 'facebook-clone-67188.firebasestorage.app',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHHXA3MQymoST6FCV313Wq9IwtVpt_ImE',
    appId: '1:763835643480:ios:537bfb1e196ef8d512bc2d',
    messagingSenderId: '763835643480',
    projectId: 'facebook-clone-67188',
    storageBucket: 'facebook-clone-67188.firebasestorage.app',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwU8AKRzNRjy-XxvkDb2GnwLNfymCSYls',
    appId: '1:763835643480:web:c85aa259c16e414412bc2d',
    messagingSenderId: '763835643480',
    projectId: 'facebook-clone-67188',
    authDomain: 'facebook-clone-67188.firebaseapp.com',
    storageBucket: 'facebook-clone-67188.firebasestorage.app',
    measurementId: 'G-HWHNBBFS2Z',
  );

}